fix: package versions have conflicting dependencies
Similar issue to: https://github.com/huggingface/transformers/pull/12961

`pip3 install -r requirements.txt` Currently fails with:

```
INFO: pip is looking at multiple versions of transformers to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 74) and huggingface-hub==0.11.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested huggingface-hub==0.11.1
    transformers 4.30.0 depends on huggingface-hub<1.0 and >=0.14.1
```